language: php
services:
  - mongodb
php:
  - 5.6
before_install: echo "extension = mongo.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
before_script:
  - composer install -n

script:
  - vendor/bin/phpunit
